<!DOCTYPE html>
<html lang="pt-BR"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-a67ac2868200dddf7a4f0e3ae403775c.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.16">

  <meta name="author" content="Prof.&nbsp;Dr.&nbsp;Thales A. C. Maia">
  <title>ELE618 - Sistemas Elétricos Industriais</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <link rel="stylesheet" href="../reveal-site-like.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" type="image/png" href="../favicon.png">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">ELE618 - Sistemas Elétricos Industriais</h1>
  <p class="subtitle">Apostila de Sistemas Elétricos Industriais - José A. Toledo Jr.<br>Seleção da Máquina Elétrica</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.&nbsp;Thales A. C. Maia 
</div>
        <p class="quarto-title-affiliation">
            UFMG - DEE
          </p>
    </div>
</div>

</section>
<section>
<section id="seleção-da-máquina-elétrica" class="title-slide slide level1 center">
<h1>Seleção da Máquina Elétrica</h1>

</section>
<section id="especificação-do-tempo-de-partida" class="slide level2">
<h2>Especificação do Tempo de Partida</h2>
<p>O sistema acelera enquanto <span class="math inline">\(T_{\rm{ac}} &gt; 0\)</span>. O tempo de aceleração <span class="math inline">\(t_{\rm{ac}}\)</span> (repouso até regime permanente) importa para:</p>
<ul>
<li>verificar se o motor consegue acionar a carga;</li>
<li>dimensionar instalação, partida e proteção;</li>
<li>calcular disponibilidade de potência mediante partidas/frenagens/reversões.</li>
</ul>
<p>As normas ABNT NBR 17094 / IEC 60034-1 exigem que o motor suporte 2 partidas sucessivas (a frio + após parar) e 1 partida a quente.</p>
</section>
<section id="expressão-exata-do-tempo-de-aceleração" class="slide level2">
<h2>Expressão Exata do Tempo de Aceleração</h2>
<p>Integrando a equação de Newton de <span class="math inline">\(0\)</span> até <span class="math inline">\(t_{\rm{ac}}\)</span>:</p>
<p><span id="eq-tacIntegral"><span class="math display">\[
t_{\rm{ac}} = \int_{0}^{t_{\rm{ac}}} dt = \int_{0}^{\omega_{\rm{op}}} \dfrac{J}{T_{\rm{ac}}(\omega_{\rm{mec}})}\, d\omega_{\rm{mec}}
\tag{1}\]</span></span></p>
<p><span class="math inline">\(T_{\rm{ac}}(\omega_{\rm{mec}})\)</span> vem da subtração das curvas de torque eletromagnético e de carga — expressá-la analiticamente (e integrar sua inversa) raramente é trivial.</p>
</section>
<section id="método-dos-intervalos-torque-médio" class="slide level2">
<h2>Método dos Intervalos (Torque Médio)</h2>
<p>Divide-se a curva de aceleração em intervalos, usando um torque médio <span class="math inline">\(\overline{T}_{\rm{ac},i}\)</span> em cada um:</p>
<div id="fig-curvaAceleracaoIntervalos" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-curvaAceleracaoIntervalos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/curvaAceleracaoIntervalos.svg" class="quarto-figure quarto-figure-center" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curvaAceleracaoIntervalos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;1: Divisão em intervalos da curva de aceleração.
</figcaption>
</figure>
</div>
</section>
<section id="método-dos-intervalos-torque-médio-1" class="slide level2">
<h2>Método dos Intervalos (Torque Médio)</h2>
<p><span id="eq-tacIntervalo"><span class="math display">\[
\overline{T}_{\rm{ac},i} = \dfrac{T_{i+1} + T_{i}}{2}, \qquad
t_{\rm{ac},i} = \dfrac{J}{\overline{T}_{\rm{ac},i}} (\omega_{i+1} - \omega_{i})
\tag{2}\]</span></span></p>
<p><span class="math display">\[
t_{\rm{ac}} = \sum_{i} t_{\rm{ac},i}
\]</span></p>
<p>Mamede Filho recomenda incrementos de 10% da velocidade síncrona, exceto onde o torque varia acentuadamente.</p>

<aside><div>
<p><strong>De onde vem a média aritmética?</strong> É a aproximação mais simples para a integral exata (<a href="#/eq-tacIntegral" class="quarto-xref">Equação&nbsp;1</a>) dentro de um intervalo pequeno: assume-se que <span class="math inline">\(T_{\rm{ac}}(\omega)\)</span> é aproximadamente <strong>constante</strong>, igual à média dos dois valores nas bordas do intervalo. Quanto menor o intervalo, melhor essa aproximação — por isso a recomendação de incrementos pequenos (10% da velocidade síncrona). O torque efetivo (próximo slide) é uma versão mais precisa da mesma ideia.</p>
</div></aside></section>
<section id="exemplo-tempo-de-aceleração-pelo-método-dos-intervalos" class="slide level2">
<h2>Exemplo: Tempo de Aceleração pelo Método dos Intervalos</h2>
<p>Acionamento com <span class="math inline">\(J=0{,}5\)</span> kg.m², velocidade de operação <span class="math inline">\(\omega_{\rm{op}}=180\)</span> rad/s, dividida em 5 intervalos iguais. Torque de aceleração (<span class="math inline">\(T_e - T_L\)</span>) em cada ponto:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(\omega\)</span> (rad/s)</th>
<th>0</th>
<th>36</th>
<th>72</th>
<th>108</th>
<th>144</th>
<th>180</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(T_{\rm{ac}}\)</span> (N.m)</td>
<td>80</td>
<td>60</td>
<td>50</td>
<td>70</td>
<td>90</td>
<td>40</td>
</tr>
</tbody>
</table>
<div id="d5f98a65" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href=""></a>omega <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">36.0</span>, <span class="fl">72.0</span>, <span class="fl">108.0</span>, <span class="fl">144.0</span>, <span class="fl">180.0</span>]  <span class="co"># rad/s</span></span>
<span id="cb1-2"><a href=""></a>Tac   <span class="op">=</span> [<span class="fl">80.0</span>, <span class="fl">60.0</span>, <span class="fl">50.0</span>, <span class="fl">70.0</span>, <span class="fl">90.0</span>, <span class="fl">40.0</span>]     <span class="co"># N.m</span></span>
<span id="cb1-3"><a href=""></a>J <span class="op">=</span> <span class="fl">0.5</span>   <span class="co"># kg.m^2</span></span>
<span id="cb1-4"><a href=""></a></span>
<span id="cb1-5"><a href=""></a>tac_total <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-6"><a href=""></a><span class="cf">for</span> k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(omega)<span class="op">-</span><span class="fl">1</span></span>
<span id="cb1-7"><a href=""></a>    Tbar <span class="op">=</span> (Tac[k<span class="op">+</span><span class="fl">1</span>] <span class="op">+</span> Tac[k]) <span class="op">/</span> <span class="fl">2</span></span>
<span id="cb1-8"><a href=""></a>    dt <span class="op">=</span> J <span class="op">/</span> Tbar <span class="op">*</span> (omega[k<span class="op">+</span><span class="fl">1</span>] <span class="op">-</span> omega[k])</span>
<span id="cb1-9"><a href=""></a>    <span class="kw">global</span> tac_total <span class="op">+=</span> dt</span>
<span id="cb1-10"><a href=""></a>    <span class="fu">println</span>(<span class="st">"intervalo "</span>, k, <span class="st">": T_medio = "</span>, <span class="fu">round</span>(Tbar, digits<span class="op">=</span><span class="fl">2</span>), <span class="st">" N.m, dt = "</span>, <span class="fu">round</span>(dt, digits<span class="op">=</span><span class="fl">4</span>), <span class="st">" s"</span>)</span>
<span id="cb1-11"><a href=""></a><span class="cf">end</span></span>
<span id="cb1-12"><a href=""></a><span class="fu">println</span>(<span class="st">"t_ac total = "</span>, <span class="fu">round</span>(tac_total, digits<span class="op">=</span><span class="fl">4</span>), <span class="st">" s"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>intervalo 1: T_medio = 70.0 N.m, dt = 0.2571 s
intervalo 2: T_medio = 55.0 N.m, dt = 0.3273 s
intervalo 3: T_medio = 60.0 N.m, dt = 0.3 s
intervalo 4: T_medio = 80.0 N.m, dt = 0.225 s
intervalo 5: T_medio = 65.0 N.m, dt = 0.2769 s
t_ac total = 1.3863 s</code></pre>
</div>
</div>
</section>
<section id="refinamento-torque-de-aceleração-efetivo" class="slide level2">
<h2>Refinamento: Torque de Aceleração Efetivo</h2>
<p>Lobosco e Dias (1988) substituem o torque médio por um torque <strong>efetivo</strong>:</p>
<p><span id="eq-Tacef"><span class="math display">\[
T_{\rm{ac,ef},i} = \dfrac{T_{i+1} - T_{i}}{\ln{ \left( \dfrac{T_{i+1}}{T_{i}} \right) }}
\tag{3}\]</span></span></p>
<p>Método mais preciso, mas com singularidade matemática quando <span class="math inline">\(T_{i+1}=T_i\)</span> ou quando algum torque é nulo.</p>

<aside><div>
<p><strong>De onde vem o <span class="math inline">\(\ln\)</span>?</strong> Da integral exata (<a href="#/eq-tacIntegral" class="quarto-xref">Equação&nbsp;1</a>), assumindo que <span class="math inline">\(T_{\rm{ac}}(\omega)\)</span> varia <strong>linearmente</strong> com <span class="math inline">\(\omega\)</span> dentro do intervalo (de <span class="math inline">\(T_i\)</span> até <span class="math inline">\(T_{i+1}\)</span>). Substituindo a variável de integração de <span class="math inline">\(\omega\)</span> para <span class="math inline">\(T\)</span>, a integral <span class="math inline">\(\int d\omega / T_{\rm{ac}}(\omega)\)</span> vira <span class="math inline">\(\int dT/T = \ln T\)</span> — daí o logaritmo. O resultado é a <strong>média logarítmica</strong> de <span class="math inline">\(T_i\)</span> e <span class="math inline">\(T_{i+1}\)</span>: mais precisa que a média aritmética simples da <a href="#/eq-tacIntervalo" class="quarto-xref">Equação&nbsp;2</a>, que assume <span class="math inline">\(T_{\rm{ac}}\)</span> constante (igual ao valor médio) dentro do intervalo, em vez de variando ponto a ponto.</p>
</div></aside></section>
<section id="exemplo-torque-efetivo-vs.-torque-médio" class="slide level2">
<h2>Exemplo: Torque Efetivo <em>vs.</em> Torque Médio</h2>
<p>Para um intervalo entre <span class="math inline">\(T_i = 80\)</span> N.m e <span class="math inline">\(T_{i+1} = 60\)</span> N.m, compare o torque médio simples com o torque efetivo de Lobosco:</p>
<div id="7e64f9dd" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href=""></a>Ti, Tip1 <span class="op">=</span> <span class="fl">80.0</span>, <span class="fl">60.0</span></span>
<span id="cb3-2"><a href=""></a></span>
<span id="cb3-3"><a href=""></a>Tmedio <span class="op">=</span> (Ti <span class="op">+</span> Tip1) <span class="op">/</span> <span class="fl">2</span></span>
<span id="cb3-4"><a href=""></a>Tef <span class="op">=</span> (Tip1 <span class="op">-</span> Ti) <span class="op">/</span> <span class="fu">log</span>(Tip1 <span class="op">/</span> Ti)</span>
<span id="cb3-5"><a href=""></a></span>
<span id="cb3-6"><a href=""></a><span class="fu">println</span>(<span class="st">"T medio    = "</span>, Tmedio, <span class="st">" N.m"</span>)</span>
<span id="cb3-7"><a href=""></a><span class="fu">println</span>(<span class="st">"T efetivo  = "</span>, <span class="fu">round</span>(Tef, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T medio    = 70.0 N.m
T efetivo  = 69.521 N.m</code></pre>
</div>
</div>
<p>A diferença entre os dois métodos é pequena (menos de 1% neste intervalo) — por isso, na prática, o método do torque médio simples costuma ser suficiente, reservando-se o torque efetivo para os casos em que se busca maior precisão.</p>
</section>
<section id="método-simplificado-torque-médio-único" class="slide level2">
<h2>Método Simplificado (Torque Médio Único)</h2>
<p>Na prática, um único valor médio para todo o acionamento é suficiente:</p>
<p><span id="eq-tacSimplificado"><span class="math display">\[
\overline{T}_{\rm{ac}} = \overline{T}_{\rm{e}} - \overline{T}_{\rm{L}}, \qquad
t_{\rm{ac}} = \dfrac{J~\omega_{\rm{op}}}{\overline{T}_{\rm{ac}}}
\tag{4}\]</span></span></p>
<p>Para motores de indução de 2 polos, Lobosco e Dias recomendam acrescentar 10% ao tempo calculado (baixo torque mínimo típico desses motores).</p>
<div id="fig-curvasConjugadoMedio" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-curvasConjugadoMedio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/curvasConjugadoMedio.svg" class="quarto-figure quarto-figure-center" style="width:48.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curvasConjugadoMedio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;2: Representação do torque médio de aceleração.
</figcaption>
</figure>
</div>

<aside><div>
<p>É o mesmo método dos intervalos (<a href="#/eq-tacIntervalo" class="quarto-xref">Equação&nbsp;2</a>), levado ao limite de <strong>um único intervalo</strong> cobrindo toda a aceleração (de <span class="math inline">\(0\)</span> a <span class="math inline">\(\omega_{\rm{op}}\)</span>) — troca-se precisão por simplicidade de cálculo. Já os 10% extra para motores de 2 polos <strong>são</strong> empíricos: uma margem de segurança de Lobosco e Dias para compensar o torque mínimo tipicamente baixo desses motores, que o método (baseado só nas médias) não capta diretamente.</p>
</div></aside></section>
<section id="torque-médio-eletromagnético-aproximação" class="slide level2">
<h2>Torque Médio Eletromagnético (Aproximação)</h2>
<p>Com <span class="math inline">\(T_{\rm{e,p}}\)</span> e <span class="math inline">\(T_{\rm{e,max}}\)</span> (torques de partida e máximo do motor):</p>
<p><span id="eq-torqueMedioEletromagnetico"><span class="math display">\[
\overline{T}_{\rm{e}} =
\begin{cases}
0{,}45 \left( T_{\rm{e,p}} + T_{\rm{e,max}} \right), &amp; \text{categorias N e H;} \\
0{,}60~T_{\rm{e,p}}, &amp; \text{categoria D.}
\end{cases}
\tag{5}\]</span></span></p>

<ul>
<li><strong>N/H:</strong> uma média simples seria <span class="math inline">\(0{,}5(T_{\rm{e,p}}+T_{\rm{e,max}})\)</span>. O coeficiente real (0,45) é <strong>menor</strong> porque, entre a partida e o torque máximo, a curva desses motores passa por um <strong>torque mínimo</strong> (<span class="math inline">\(T_{\rm{min}}\)</span>) — a curva “afunda” no meio do caminho antes de subir até <span class="math inline">\(T_{\rm{max}}\)</span>. Isso puxa a média real (pela área sob a curva) para baixo da média ingênua dos dois extremos.</li>
<li><strong>D:</strong> motores de categoria D têm curva de torque decrescente da partida até a operação, sem esse afundamento pronunciado — por isso a aproximação usa só <span class="math inline">\(T_{\rm{e,p}}\)</span> (nem precisa de <span class="math inline">\(T_{\rm{e,max}}\)</span>), escalado por 0,6.</li>
</ul>
<aside><div>
<p><strong>De onde vêm 0,45 e 0,60?</strong> Ao contrário do <span class="math inline">\(\ln\)</span> do torque efetivo (Lobosco), aqui <strong>não há uma integral fechada por trás</strong> — são coeficientes <strong>empíricos</strong>, ajustados por Augusto Júnior (2005) e Mamede Filho (2017) a partir de curvas reais de torque × velocidade.</p>
</div></aside></section>
<section id="exemplo-torque-médio-eletromagnético" class="slide level2">
<h2>Exemplo: Torque Médio Eletromagnético</h2>
<p>Motor categoria N com <span class="math inline">\(T_{\rm{e,p}} = 180\)</span> N.m e <span class="math inline">\(T_{\rm{e,max}} = 220\)</span> N.m. Compare com um motor categoria D de mesmo <span class="math inline">\(T_{\rm{e,p}}' = 160\)</span> N.m:</p>
<div id="bd0f5e08" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href=""></a>Tep, Temax <span class="op">=</span> <span class="fl">180.0</span>, <span class="fl">220.0</span>   <span class="co"># motor categoria N/H</span></span>
<span id="cb5-2"><a href=""></a>Tebar_NH <span class="op">=</span> <span class="fl">0.45</span> <span class="op">*</span> (Tep <span class="op">+</span> Temax)</span>
<span id="cb5-3"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e_bar (N/H) = "</span>, Tebar_NH, <span class="st">" N.m"</span>)</span>
<span id="cb5-4"><a href=""></a></span>
<span id="cb5-5"><a href=""></a>Tep_D <span class="op">=</span> <span class="fl">160.0</span>               <span class="co"># motor categoria D</span></span>
<span id="cb5-6"><a href=""></a>Tebar_D <span class="op">=</span> <span class="fl">0.60</span> <span class="op">*</span> Tep_D</span>
<span id="cb5-7"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e_bar (D)   = "</span>, Tebar_D, <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T_e_bar (N/H) = 180.0 N.m
T_e_bar (D)   = 96.0 N.m</code></pre>
</div>
</div>
</section>
<section id="correção-para-partida-com-tensão-reduzida" class="slide level2">
<h2>Correção para Partida com Tensão Reduzida</h2>
<p>Com <span class="math inline">\(k = V_{\rm{red}} / V_{\rm{nom}}\)</span>:</p>
<p><span id="eq-torqueMedioReduzida"><span class="math display">\[
\overline{T}_{\rm{e}} =
\begin{cases}
0{,}45 \left( T_{\rm{e,p}}\, k^{2{,}2} + T_{\rm{e,max}}\, k^{2{,}0} \right), &amp; \text{categorias N e H;} \\
0{,}60~T_{\rm{e,p}}\, k^{2{,}2}, &amp; \text{categoria D.}
\end{cases}
\tag{6}\]</span></span></p>

<aside><div>
<p><strong>De onde vêm os expoentes <span class="math inline">\(2{,}2\)</span> e <span class="math inline">\(2{,}0\)</span>?</strong> A base é física: num motor de indução, a corrente do rotor é proporcional à tensão aplicada (<span class="math inline">\(I \propto V\)</span>, circuito linear equivalente), e o torque depende do quadrado dessa corrente (<span class="math inline">\(T \propto I^2\)</span>) — logo <span class="math inline">\(T \propto V^2\)</span> em qualquer escorregamento, com frequência fixa.</p>
<ul>
<li><strong><span class="math inline">\(T_{\rm{e,max}}\)</span> (<span class="math inline">\(k^{2{,}0}\)</span>):</strong> segue exatamente essa lei quadrática ideal — o torque máximo é bem descrito pelo circuito equivalente linear mesmo com tensão reduzida.</li>
<li><strong><span class="math inline">\(T_{\rm{e,p}}\)</span> (<span class="math inline">\(k^{2{,}2}\)</span>):</strong> aqui o expoente <span class="math inline">\(2{,}2\)</span> (em vez de <span class="math inline">\(2{,}0\)</span>) já é <strong>ajuste empírico</strong>, não dedução. Na partida (rotor bloqueado), a corrente é muito mais alta e a máquina satura magneticamente mais — isso faz o torque de partida cair um pouco mais rápido que a lei quadrática ideal quando a tensão é reduzida, daí o expoente levemente maior.</li>
</ul>
</div></aside></section>
<section id="exemplo-partida-estrela-triângulo" class="slide level2">
<h2>Exemplo: Partida Estrela-Triângulo</h2>
<p>Na ligação estrela-triângulo, o enrolamento vê <span class="math inline">\(1/\sqrt{3} \approx 57{,}7\%\)</span> da tensão de linha durante a partida. Para o motor N/H do exemplo anterior (<span class="math inline">\(T_{\rm{e,p}}=180\)</span>, <span class="math inline">\(T_{\rm{e,max}}=220\)</span> N.m):</p>
<div id="3c9b13f9" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href=""></a>Tep, Temax <span class="op">=</span> <span class="fl">180.0</span>, <span class="fl">220.0</span></span>
<span id="cb7-2"><a href=""></a>k <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fu">sqrt</span>(<span class="fl">3</span>)</span>
<span id="cb7-3"><a href=""></a><span class="fu">println</span>(<span class="st">"k = Vred/Vnom = "</span>, <span class="fu">round</span>(k, digits<span class="op">=</span><span class="fl">4</span>))</span>
<span id="cb7-4"><a href=""></a></span>
<span id="cb7-5"><a href=""></a>Tebar_reduzida <span class="op">=</span> <span class="fl">0.45</span> <span class="op">*</span> (Tep <span class="op">*</span> k<span class="op">^</span><span class="fl">2.2</span> <span class="op">+</span> Temax <span class="op">*</span> k<span class="op">^</span><span class="fl">2.0</span>)</span>
<span id="cb7-6"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e_bar com partida estrela = "</span>, <span class="fu">round</span>(Tebar_reduzida, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" N.m"</span>)</span>
<span id="cb7-7"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e_bar em tensao plena     = "</span>, <span class="fl">0.45</span><span class="fu">*</span>(Tep<span class="op">+</span>Temax), <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>k = Vred/Vnom = 0.5774
T_e_bar com partida estrela = 57.191 N.m
T_e_bar em tensao plena     = 180.0 N.m</code></pre>
</div>
</div>
<p>A partida estrela-triângulo reduz o torque médio eletromagnético disponível para menos de <strong>um terço</strong> do valor em tensão plena — por isso ela só é viável quando a carga tem baixo torque de partida.</p>
</section>
<section id="torque-médio-de-carga" class="slide level2">
<h2>Torque Médio de Carga</h2>
<p>Com <span class="math inline">\(\beta\)</span> dependendo da natureza da carga (0: constante, 1: linear, 2: quadrática — Seção anterior):</p>
<p><span id="eq-torqueMedioCarga"><span class="math display">\[
\overline{T}_{\rm{L}} = T_{\rm{L,p}} + \dfrac{\left( T_{\rm{L,op}} - T_{\rm{L,p}} \right)}{\beta + 1}
\tag{7}\]</span></span></p>
<p>Para torque inverso à rotação, o valor médio é problemático (inspeção visual/computacional); para torque não uniforme, é particular a cada aplicação; para cargas sem torque, é nulo.</p>

<aside><div>
<p><strong>Esta, ao contrário de várias outras, tem dedução fechada.</strong> Modelando a carga como <span class="math inline">\(T_{\rm{L}}(\omega) = T_{\rm{L,p}} + \alpha_{\rm{L}}\,\omega^{\beta}\)</span>, a média integral em <span class="math inline">\([0,\omega_{\rm{op}}]\)</span> é <span class="math inline">\(T_{\rm{L,p}} + \alpha_{\rm{L}}\,\omega_{\rm{op}}^{\beta}/(\beta+1)\)</span>. Como <span class="math inline">\(T_{\rm{L,op}} = T_{\rm{L,p}} + \alpha_{\rm{L}}\,\omega_{\rm{op}}^{\beta}\)</span> (a própria definição de <span class="math inline">\(T_{\rm{L,op}}\)</span>), basta substituir <span class="math inline">\(\alpha_{\rm{L}}\,\omega_{\rm{op}}^{\beta} = T_{\rm{L,op}}-T_{\rm{L,p}}\)</span> para chegar na fórmula ao lado — confirmado numericamente por integração direta.</p>
</div></aside></section>
<section id="exemplo-torque-médio-de-carga" class="slide level2">
<h2>Exemplo: Torque Médio de Carga</h2>
<p>Carga com torque linear com a rotação (<span class="math inline">\(\beta=1\)</span>), <span class="math inline">\(T_{\rm{L,p}} = 30\)</span> N.m na partida e <span class="math inline">\(T_{\rm{L,op}} = 90\)</span> N.m no ponto de operação:</p>
<div id="853de685" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href=""></a>TLp, TLop, beta <span class="op">=</span> <span class="fl">30.0</span>, <span class="fl">90.0</span>, <span class="fl">1</span></span>
<span id="cb9-2"><a href=""></a>TLbar <span class="op">=</span> TLp <span class="op">+</span> (TLop <span class="op">-</span> TLp) <span class="op">/</span> (beta <span class="op">+</span> <span class="fl">1</span>)</span>
<span id="cb9-3"><a href=""></a><span class="fu">println</span>(<span class="st">"T_L_bar = "</span>, TLbar, <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T_L_bar = 60.0 N.m</code></pre>
</div>
</div>
</section>
<section id="exemplo-tempo-de-aceleração-simplificado-e-limite-de-rotor-bloqueado" class="slide level2">
<h2>Exemplo: Tempo de Aceleração Simplificado e Limite de Rotor Bloqueado</h2>
<p>Com <span class="math inline">\(\overline{T}_{\rm{e}} = 180\)</span> N.m, <span class="math inline">\(\overline{T}_{\rm{L}} = 60\)</span> N.m, <span class="math inline">\(J=0{,}5\)</span> kg.m², <span class="math inline">\(\omega_{\rm{op}}=180\)</span> rad/s, e tempo de rotor bloqueado do fabricante <span class="math inline">\(t_{\rm{rb,max}}=12\)</span> s:</p>
<div id="d679d330" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb11-1"><a href=""></a>Tebar, TLbar <span class="op">=</span> <span class="fl">180.0</span>, <span class="fl">60.0</span></span>
<span id="cb11-2"><a href=""></a>J, omega_op <span class="op">=</span> <span class="fl">0.5</span>, <span class="fl">180.0</span></span>
<span id="cb11-3"><a href=""></a></span>
<span id="cb11-4"><a href=""></a>Tacbar <span class="op">=</span> Tebar <span class="op">-</span> TLbar</span>
<span id="cb11-5"><a href=""></a>tac_simpl <span class="op">=</span> J <span class="op">*</span> omega_op <span class="op">/</span> Tacbar</span>
<span id="cb11-6"><a href=""></a><span class="fu">println</span>(<span class="st">"t_ac simplificado = "</span>, <span class="fu">round</span>(tac_simpl, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" s"</span>)</span>
<span id="cb11-7"><a href=""></a></span>
<span id="cb11-8"><a href=""></a>trb_max <span class="op">=</span> <span class="fl">12.0</span></span>
<span id="cb11-9"><a href=""></a>limite <span class="op">=</span> <span class="fl">0.8</span> <span class="op">*</span> trb_max</span>
<span id="cb11-10"><a href=""></a><span class="fu">println</span>(<span class="st">"limite 0,8 * t_rb_max = "</span>, limite, <span class="st">" s -&gt; "</span>, tac_simpl <span class="op">&lt;=</span> limite ? <span class="st">"atende"</span> <span class="op">:</span> <span class="st">"excede"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>t_ac simplificado = 0.75 s
limite 0,8 * t_rb_max = 9.600000000000001 s -&gt; atende</code></pre>
</div>
</div>
</section>
<section id="classe-de-isolamento-e-vida-útil" class="slide level2">
<h2>Classe de Isolamento e Vida Útil</h2>
<p><span class="math display">\[
t_{\rm{ac}} \leq 0{,}8~t_{\rm{rb,max}}
\]</span></p>
<p>Se o motor não atinge <span class="math inline">\(\omega_{\rm{op}}\)</span> nesse prazo, a corrente de estator (6 a 9 vezes a nominal) aquece perigosamente o enrolamento.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Classe de isolamento</th>
<th>A</th>
<th>E</th>
<th>B</th>
<th>F</th>
<th>H</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temperatura ambiente (°C)</td>
<td>40</td>
<td>40</td>
<td>40</td>
<td>40</td>
<td>40</td>
</tr>
<tr class="even">
<td>Elevação de temperatura <span class="math inline">\(\Delta t\)</span> (°C)</td>
<td>60</td>
<td>75</td>
<td>80</td>
<td>105</td>
<td>125</td>
</tr>
<tr class="odd">
<td>Diferença ponto mais quente / média (°C)</td>
<td>5</td>
<td>5</td>
<td>10</td>
<td>10</td>
<td>15</td>
</tr>
<tr class="even">
<td>Temperatura total (°C)</td>
<td>105</td>
<td>120</td>
<td>130</td>
<td>155</td>
<td>180</td>
</tr>
</tbody>
</table>
<p>Um aumento de 8 a 10 °C acima do limite da classe pode reduzir a vida útil do enrolamento pela metade.</p>

<aside><div>
<p>Os <span class="math inline">\(0{,}8\)</span> do limite de rotor bloqueado e todos os valores da tabela são <strong>normativos/empíricos</strong> — não vêm de uma fórmula, vêm de normas (ABNT/IEC) e de dados de degradação de materiais isolantes reais (o verniz isolante envelhece e perde a capacidade de isolar em função da temperatura e do tempo de exposição — uma relação estudada empiricamente e resumida nesses limites por classe).</p>
</div></aside></section>
<section id="especificação-da-potência-mecânica" class="slide level2">
<h2>Especificação da Potência Mecânica</h2>
<p>Potência de um agente que desenvolve torque: <span class="math inline">\(P(t) = T(t)\,\omega(t)\)</span>. Multiplicando a Eq. de Newton por <span class="math inline">\(\omega_{\rm{mec}}(t)\)</span>:</p>
<p><span id="eq-relacoesPotencia"><span class="math display">\[
\underbrace{T_{\rm{e}}(t) \omega_{\rm{mec}}(t)}_{P_{\rm{mec}}(t)} = \underbrace{T_{\rm{L}}(t) \omega_{\rm{mec}}(t)}_{P_{\rm{L}}(t)} + \underbrace{J \frac{d\omega_{\rm{mec}}(t)}{dt} \omega_{\rm{mec}}(t)}_{P_{\rm{ac}}(t)}
\tag{8}\]</span></span></p>

<img data-src="images/graficoTorqueVelocidadePotencia.png" class="r-stretch quarto-figure quarto-figure-center" id="fig-graficoTorqueVelocidadePotencia"><p class="caption">
Fig.&nbsp;3: Potência mecânica a partir do torque e da velocidade angular.
</p></section>
<section id="potência-de-pico-vs.-potência-eficaz" class="slide level2">
<h2>Potência de Pico <em>vs.</em> Potência Eficaz</h2>
<p>Selecionar pelo pico (≈ 42 kW / 57 cv) garante a reprodução da forma de onda, mas <strong>superdimensiona</strong> o motor. Como o motor suporta sobrecarga limitada, uma potência nominal menor pode bastar — desde que calculada pela <strong>potência eficaz</strong> (mesmas perdas/elevação de temperatura que a potência cíclica variável):</p>
<p><span id="eq-PefIntegral"><span class="math display">\[
P_{\rm{ef}} = \sqrt{ \dfrac{1}{T} \int^{T}_{0} P_{\rm{mec}}(t)^{2}\, dt }
\tag{9}\]</span></span></p>
<p>Para o ciclo da <a href="#/fig-graficoTorqueVelocidadePotencia" class="quarto-xref">Figura&nbsp;3</a>, <span class="math inline">\(P_{\rm{ef}} = 26{,}8\)</span> kW — o que leva à escolha de um motor comercial de <strong>40 cv</strong>, em vez dos 60 cv do valor de pico.</p>

<aside><div>
<p><strong>Por que essa raiz-da-média-dos-quadrados (RMS)?</strong> É a mesma lógica da corrente RMS em circuitos elétricos: as perdas por efeito Joule crescem com o <strong>quadrado</strong> da corrente (e, numa faixa de operação razoável, com o quadrado da potência). Uma potência constante <span class="math inline">\(P_{\rm{ef}}\)</span> causa o mesmo aquecimento médio que a potência cíclica variável real quando ambas têm o mesmo valor médio quadrático — daí elevar ao quadrado, integrar/tirar a média, e depois tirar a raiz.</p>
</div></aside></section>
<section id="regimes-de-serviço" class="slide level2">
<h2>Regimes de Serviço</h2>
<p>Com o ciclo conhecido, especifica-se o regime de serviço com precisão — 10 regimes padronizados pela NBR 17094-1 (S1 a S10):</p>
<div class="columns">
<div class="column" style="width:50%;">
<div id="fig-cicloContinuo" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-cicloContinuo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/cicloContinuoSolicitacaoIntermitente.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cicloContinuo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;4: Funcionamento contínuo com solicitações intermitentes.
</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div id="fig-cicloVariavel" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-cicloVariavel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/cicloVariavelRepouso.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cicloVariavel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;5: Carga variável com repouso entre os tempos de carga.
</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="regimes-s1-contínuo-e-s8" class="slide level2">
<h2>Regimes S1 (Contínuo) e S8</h2>
<div class="columns">
<div class="column" style="width:45%;">
<div id="fig-regimeS1" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-regimeS1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/regimeS1.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regimeS1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;6: Regime S1: carga constante até equilíbrio térmico.
</figcaption>
</figure>
</div>
</div><div class="column" style="width:55%;">
<div id="fig-regimeS8" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-regimeS8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/regimeS8.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regimeS8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;7: Regime S8: funcionamento contínuo com mudança periódica carga/velocidade, sem repouso.
</figcaption>
</figure>
</div>
</div></div>
<p>Em nenhum dos 10 regimes a temperatura do motor ultrapassa <span class="math inline">\(\theta_{\rm{max}}\)</span> da isolação.</p>
</section>
<section id="simplificações-práticas" class="slide level2">
<h2>Simplificações Práticas</h2>
<ul>
<li><strong>Carga de pequena inércia:</strong> <span class="math inline">\(P_{\rm{mec}}(t) \approx P_{\rm{L}}(t)\)</span> (potência de aceleração desprezível);</li>
<li><strong>Cargas constantes por trechos</strong> (comum na indústria) simplifica a integral em um somatório:</li>
</ul>
<p><span id="eq-PefSemRepouso"><span class="math display">\[
P_{\rm{ef}} = \sqrt{ \dfrac{ \sum P_{\rm{L},i}(t)^{2} \cdot t_{i} }{ \sum t_{i} } }
\tag{10}\]</span></span></p>
<p>Válida para motores que giram continuamente (sem repouso entre cargas).</p>

<aside><div>
<p>Sem novidade matemática: é a <a href="#/eq-PefIntegral" class="quarto-xref">Equação&nbsp;9</a> discretizada — quando a carga é constante por trechos, a integral <span class="math inline">\(\int P(t)^2\,dt\)</span> vira exatamente uma soma de retângulos <span class="math inline">\(\sum P_{L,i}^2\,t_i\)</span>, sem nenhuma aproximação extra.</p>
</div></aside></section>
<section id="exemplo-potência-eficaz-sem-repouso" class="slide level2">
<h2>Exemplo: Potência Eficaz sem Repouso</h2>
<p>Ciclo de carga com 3 patamares:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Patamar</th>
<th><span class="math inline">\(P_L\)</span> (kW)</th>
<th>Duração (s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>10</td>
<td>20</td>
</tr>
<tr class="even">
<td>2</td>
<td>25</td>
<td>30</td>
</tr>
<tr class="odd">
<td>3</td>
<td>15</td>
<td>10</td>
</tr>
</tbody>
</table>
<div id="45cf53ee" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb13-1"><a href=""></a>PLi <span class="op">=</span> [<span class="fl">10.0</span>, <span class="fl">25.0</span>, <span class="fl">15.0</span>]   <span class="co"># kW</span></span>
<span id="cb13-2"><a href=""></a>ti  <span class="op">=</span> [<span class="fl">20.0</span>, <span class="fl">30.0</span>, <span class="fl">10.0</span>]   <span class="co"># s</span></span>
<span id="cb13-3"><a href=""></a></span>
<span id="cb13-4"><a href=""></a>Pef <span class="op">=</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(PLi<span class="op">.^</span><span class="fl">2</span> <span class="op">.*</span> ti) <span class="op">/</span> <span class="fu">sum</span>(ti))</span>
<span id="cb13-5"><a href=""></a><span class="fu">println</span>(<span class="st">"P_ef = "</span>, <span class="fu">round</span>(Pef, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" kW  (pico = "</span>, <span class="fu">maximum</span>(PLi), <span class="st">" kW)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P_ef = 19.579 kW  (pico = 25.0 kW)</code></pre>
</div>
</div>
</section>
<section id="ciclo-com-repouso-k_rmv" class="slide level2">
<h2>Ciclo com Repouso (<span class="math inline">\(k_{\rm{v}}\)</span>)</h2>
<p>Motores autoventilados esfriam pior parados. Com tempo de repouso <span class="math inline">\(t_{\rm{r}}\)</span> e <span class="math inline">\(k_{\rm{v}}\)</span> (1: ventilação independente do funcionamento — 3: ventilação vinculada ao funcionamento):</p>
<p><span id="eq-PefComRepouso"><span class="math display">\[
P_{\rm{ef}} = \sqrt{ \dfrac{ \sum P_{\rm{L},i}(t)^{2} \cdot t_{i} }{ \sum t_{i} + \dfrac{t_{r}}{k_{\rm{v}}} } }
\tag{11}\]</span></span></p>

<aside><div>
<p>O termo <span class="math inline">\(t_r/k_{\rm{v}}\)</span> é uma <strong>correção empírica</strong>, não uma dedução: fisicamente, o repouso deveria contar como tempo “de graça” para resfriar (reduzindo a potência efetiva necessária), mas só na medida em que a ventilação continue funcionando parada. <span class="math inline">\(k_{\rm{v}}\)</span> pondera esse efeito — quanto maior <span class="math inline">\(k_{\rm{v}}\)</span> (motor autoventilado, ventilação para junto com o eixo), menos o repouso ajuda a resfriar, e por isso menos ele “conta” no denominador.</p>
</div></aside></section>
<section id="exemplo-potência-eficaz-com-repouso" class="slide level2">
<h2>Exemplo: Potência Eficaz com Repouso</h2>
<p>Ao ciclo de 3 patamares, acrescente um repouso de <span class="math inline">\(t_r = 15\)</span> s, com motor autoventilado (<span class="math inline">\(k_v = 3\)</span>):</p>
<div id="de1cb26c" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb15-1"><a href=""></a>PLi <span class="op">=</span> [<span class="fl">10.0</span>, <span class="fl">25.0</span>, <span class="fl">15.0</span>]</span>
<span id="cb15-2"><a href=""></a>ti  <span class="op">=</span> [<span class="fl">20.0</span>, <span class="fl">30.0</span>, <span class="fl">10.0</span>]</span>
<span id="cb15-3"><a href=""></a>tr, kv <span class="op">=</span> <span class="fl">15.0</span>, <span class="fl">3.0</span></span>
<span id="cb15-4"><a href=""></a></span>
<span id="cb15-5"><a href=""></a>Pef_com_repouso <span class="op">=</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(PLi<span class="op">.^</span><span class="fl">2</span> <span class="op">.*</span> ti) <span class="op">/</span> (<span class="fu">sum</span>(ti) <span class="op">+</span> tr<span class="op">/</span>kv))</span>
<span id="cb15-6"><a href=""></a><span class="fu">println</span>(<span class="st">"P_ef (com repouso) = "</span>, <span class="fu">round</span>(Pef_com_repouso, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" kW"</span>)</span>
<span id="cb15-7"><a href=""></a><span class="fu">println</span>(<span class="st">"P_ef (sem repouso, referencia) = "</span>, <span class="fu">round</span>(<span class="fu">sqrt</span>(<span class="fu">sum</span>(PLi<span class="op">.^</span><span class="fl">2</span> <span class="op">.*</span> ti)<span class="op">/</span><span class="fu">sum</span>(ti)), digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" kW"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P_ef (com repouso) = 18.811 kW
P_ef (sem repouso, referencia) = 19.579 kW</code></pre>
</div>
</div>
<p>Com repouso, <span class="math inline">\(P_{\rm{ef}}\)</span> <strong>cai</strong> de 19,6 kW para 18,8 kW: o mesmo trabalho térmico fica distribuído em um ciclo de tempo total maior, permitindo (a princípio) um motor comercial menor. O fator <span class="math inline">\(k_{\rm{v}}=3\)</span> já penaliza esse ganho — motores autoventilados (TEFC) esfriam pouco parados, então o repouso conta menos como “tempo de resfriamento” do que contaria para um motor com ventilação forçada (<span class="math inline">\(k_{\rm{v}}=1\)</span>).</p>
</section>
<section id="condições-de-torque-do-motor-selecionado" class="slide level2">
<h2>Condições de Torque do Motor Selecionado</h2>
<p>Além da potência, o motor deve satisfazer:</p>
<p><span class="math display">\[
T_{\rm{e,p}} &gt; T_{\rm{L,p}}, \qquad T_{\rm{e,max}} &gt; 1{,}2 \cdot T_{\rm{L,max}}
\]</span></p>
<p>(regra prática: torque máximo do motor pelo menos 20% acima do maior torque resistente).</p>

<aside><div>
<p>A primeira condição (<span class="math inline">\(T_{\rm{e,p}} &gt; T_{\rm{L,p}}\)</span>) é lógica pura: sem isso o motor nem sai do repouso. Já a margem de <strong>20%</strong> na segunda condição é uma <strong>regra prática</strong> de Augusto Júnior — uma folga de segurança para picos de carga, quedas momentâneas de tensão e a própria tolerância normativa de <span class="math inline">\(-10\%\)</span> no torque máximo medido (Tab. de tolerâncias, mais adiante), não um valor deduzido analiticamente.</p>
</div></aside></section>
<section id="exemplo-verificação-das-condições-de-torque" class="slide level2">
<h2>Exemplo: Verificação das Condições de Torque</h2>
<p>Motor com <span class="math inline">\(T_{\rm{e,p}}=180\)</span> N.m e <span class="math inline">\(T_{\rm{e,max}}=220\)</span> N.m, para uma carga com <span class="math inline">\(T_{\rm{L,p}}=140\)</span> N.m e <span class="math inline">\(T_{\rm{L,max}}=170\)</span> N.m:</p>
<div id="8bcd1ece" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb17-1"><a href=""></a>Tep, TLp <span class="op">=</span> <span class="fl">180.0</span>, <span class="fl">140.0</span></span>
<span id="cb17-2"><a href=""></a>Temax, TLmax <span class="op">=</span> <span class="fl">220.0</span>, <span class="fl">170.0</span></span>
<span id="cb17-3"><a href=""></a></span>
<span id="cb17-4"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e,p &gt; T_L,p ?        "</span>, Tep <span class="op">&gt;</span> TLp, <span class="st">"   ("</span>, Tep, <span class="st">" &gt; "</span>, TLp, <span class="st">")"</span>)</span>
<span id="cb17-5"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e,max &gt; 1,2 T_L,max ? "</span>, Temax <span class="op">&gt;</span> <span class="fl">1.2</span><span class="op">*</span>TLmax, <span class="st">"  ("</span>, Temax, <span class="st">" &gt; "</span>, <span class="fu">round</span>(<span class="fl">1.2</span><span class="op">*</span>TLmax, digits<span class="op">=</span><span class="fl">1</span>), <span class="st">")"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T_e,p &gt; T_L,p ?        true   (180.0 &gt; 140.0)
T_e,max &gt; 1,2 T_L,max ? true  (220.0 &gt; 204.0)</code></pre>
</div>
</div>
</section>
<section id="redução-de-potência-partidas-frenagens-e-reversões" class="slide level2">
<h2>Redução de Potência: Partidas, Frenagens e Reversões</h2>
<p>Perdas Joule na partida/frenagem/reversão elevam a temperatura. Lobosco e Dias: uma frenagem equivale a 3 partidas; uma reversão elétrica, a 4 partidas.</p>
<p><span id="eq-PdispPFR"><span class="math display">\[
P_{\rm{disp,pfr}} = \underbrace{ \sqrt{ \dfrac{ 3600 - k_{\rm{pfr}} \cdot N_{\rm{p}} \cdot t_{\rm{ac}} \cdot \left( \dfrac{I_{\rm{p}}}{I_{\rm{nom}}} \right)^{2} }{ 3600 - 2 \cdot N_{\rm{p}} \cdot t_{\rm{ac}} } } }_{\alpha_{\rm{pfr}}} \cdot P_{\rm{nom}}
\tag{12}\]</span></span></p>
<p><span class="math inline">\(k_{\rm{pfr}}=1\)</span> (partida), <span class="math inline">\(3\)</span> (frenagem) ou <span class="math inline">\(4\)</span> (reversão); <span class="math inline">\(N_{\rm{p}}\)</span>: repetições/hora.</p>

<aside><div>
<p>Fórmula <strong>empírica</strong> de Lobosco e Dias. O <span class="math inline">\(3600\)</span> é só a conversão de unidades (segundos numa hora, já que <span class="math inline">\(N_{\rm{p}}\)</span> é em repetições/hora e <span class="math inline">\(t_{\rm{ac}}\)</span> em segundos) — isso é dimensional, não empírico. Mas os multiplicadores <span class="math inline">\(k_{\rm{pfr}}=3\)</span> (frenagem) e <span class="math inline">\(4\)</span> (reversão) <strong>são</strong> estimativas empíricas dos autores para o efeito térmico equivalente de cada operação comparado a uma partida simples — não vêm de um cálculo termodinâmico fechado, são uma simplificação prática validada por eles com dados de campo.</p>
</div></aside></section>
<section id="exemplo-potência-disponível-com-partidas-frequentes" class="slide level2">
<h2>Exemplo: Potência Disponível com Partidas Frequentes</h2>
<p>Motor de <span class="math inline">\(P_{\rm{nom}} = 50\)</span> cv, com <span class="math inline">\(N_p = 4\)</span> partidas/hora, <span class="math inline">\(t_{\rm{ac}} = 8\)</span> s, e <span class="math inline">\(I_p/I_{\rm{nom}} = 7\)</span>:</p>
<div id="4bd5f4f1" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href=""></a>kpfr <span class="op">=</span> <span class="fl">1.0</span>     <span class="co"># partida</span></span>
<span id="cb19-2"><a href=""></a>Np <span class="op">=</span> <span class="fl">4.0</span>       <span class="co"># partidas por hora</span></span>
<span id="cb19-3"><a href=""></a>tac_h <span class="op">=</span> <span class="fl">8.0</span>    <span class="co"># s</span></span>
<span id="cb19-4"><a href=""></a>Ip_Inom <span class="op">=</span> <span class="fl">7.0</span></span>
<span id="cb19-5"><a href=""></a>Pnom <span class="op">=</span> <span class="fl">50.0</span>    <span class="co"># cv</span></span>
<span id="cb19-6"><a href=""></a></span>
<span id="cb19-7"><a href=""></a>alpha_pfr <span class="op">=</span> <span class="fu">sqrt</span>((<span class="fl">3600</span> <span class="op">-</span> <span class="fu">kpfr*Np*tac_h*</span>(Ip_Inom)<span class="op">^</span><span class="fl">2</span>) <span class="op">/</span> (<span class="fl">3600</span> <span class="op">-</span> <span class="fl">2</span><span class="op">*</span>Np<span class="op">*</span>tac_h))</span>
<span id="cb19-8"><a href=""></a>Pdisp_pfr <span class="op">=</span> alpha_pfr <span class="op">*</span> Pnom</span>
<span id="cb19-9"><a href=""></a></span>
<span id="cb19-10"><a href=""></a><span class="fu">println</span>(<span class="st">"alpha_pfr = "</span>, <span class="fu">round</span>(alpha_pfr, digits<span class="op">=</span><span class="fl">4</span>))</span>
<span id="cb19-11"><a href=""></a><span class="fu">println</span>(<span class="st">"P_disp,pfr = "</span>, <span class="fu">round</span>(Pdisp_pfr, digits<span class="op">=</span><span class="fl">2</span>), <span class="st">" cv"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>alpha_pfr = 0.7581
P_disp,pfr = 37.9 cv</code></pre>
</div>
</div>
<p>Mesmo com apenas 4 partidas por hora, o fator <span class="math inline">\(\alpha_{\rm{pfr}}\)</span> reduz a potência disponível para cerca de 76% da nominal — o efeito cresce rapidamente com <span class="math inline">\(N_p\)</span>, <span class="math inline">\(t_{\rm{ac}}\)</span> e, principalmente, com o quadrado da relação <span class="math inline">\(I_p/I_{\rm{nom}}\)</span>.</p>
</section>
<section id="redução-por-ambiente-atípico" class="slide level2">
<h2>Redução por Ambiente Atípico</h2>
<p>Norma exige potência nominal sem sobreaquecimento até 1000 m de altitude e 40 °C. Acima disso, o ar rarefeito piora o arrefecimento:</p>
<p><span id="eq-PdispAmb"><span class="math display">\[
P_{\rm{disp,amb}} = \alpha_{\rm{amb}} \cdot P_{\rm{nom}}
\tag{13}\]</span></span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(T_{\rm{amb}}\)</span> (°C) / <span class="math inline">\(H\)</span> (m)</th>
<th>1000</th>
<th>2000</th>
<th>3000</th>
<th>4000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30</td>
<td>—</td>
<td>1,00</td>
<td>0,92</td>
<td>0,86</td>
</tr>
<tr class="even">
<td>40</td>
<td>1,00</td>
<td>0,94</td>
<td>0,86</td>
<td>0,80</td>
</tr>
<tr class="odd">
<td>50</td>
<td>0,92</td>
<td>0,87</td>
<td>0,82</td>
<td>0,77</td>
</tr>
</tbody>
</table>
<p>(Tabela completa da WEG tem também 1500, 2500, 3500, 4500 e 5000 m — aqui reduzida para caber no slide.)</p>

<aside><div>
<p>Tabela <strong>100% empírica</strong>, do fabricante (WEG): os valores de <span class="math inline">\(\alpha_{\rm{amb}}\)</span> vêm de testes/modelos térmicos da própria WEG relacionando a capacidade de dissipação de calor real do ar (que piora com altitude e temperatura) à potência que o motor consegue entregar sem sobreaquecer. Não há uma fórmula fechada por trás — é uma tabela de engenharia, específica do fabricante.</p>
</div></aside></section>
<section id="exemplo-correção-ambiental" class="slide level2">
<h2>Exemplo: Correção Ambiental</h2>
<p>Motor de 50 cv instalado a 2000 m de altitude, com temperatura ambiente de 40 °C (<span class="math inline">\(\alpha_{\rm{amb}} = 0{,}94\)</span>, pela tabela):</p>
<div id="b5094186" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href=""></a>alpha_amb <span class="op">=</span> <span class="fl">0.94</span>   <span class="co"># tabela: Tamb=40C, H=2000m</span></span>
<span id="cb21-2"><a href=""></a>Pnom <span class="op">=</span> <span class="fl">50.0</span>        <span class="co"># cv</span></span>
<span id="cb21-3"><a href=""></a></span>
<span id="cb21-4"><a href=""></a>Pdisp_amb <span class="op">=</span> alpha_amb <span class="op">*</span> Pnom</span>
<span id="cb21-5"><a href=""></a><span class="fu">println</span>(<span class="st">"P_disp,amb = "</span>, Pdisp_amb, <span class="st">" cv"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P_disp,amb = 47.0 cv</code></pre>
</div>
</div>
</section>
<section id="correção-total" class="slide level2">
<h2>Correção Total</h2>
<p>Quando há partidas frequentes <strong>e</strong> ambiente atípico simultaneamente:</p>
<p><span id="eq-PdispTotal"><span class="math display">\[
P_{\rm{disp,total}} = \alpha_{\rm{pfr}} \cdot \alpha_{\rm{amb}} \cdot P_{\rm{nom}}
\tag{14}\]</span></span></p>

<div id="69d4cb9f" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href=""></a>alpha_pfr <span class="op">=</span> <span class="fl">0.7581</span>   <span class="co"># do exemplo de partidas sucessivas</span></span>
<span id="cb23-2"><a href=""></a>alpha_amb <span class="op">=</span> <span class="fl">0.94</span>     <span class="co"># do exemplo de correcao ambiental</span></span>
<span id="cb23-3"><a href=""></a>Pnom <span class="op">=</span> <span class="fl">50.0</span></span>
<span id="cb23-4"><a href=""></a></span>
<span id="cb23-5"><a href=""></a>Pdisp_total <span class="op">=</span> alpha_pfr <span class="op">*</span> alpha_amb <span class="op">*</span> Pnom</span>
<span id="cb23-6"><a href=""></a><span class="fu">println</span>(<span class="st">"P_disp,total = "</span>, <span class="fu">round</span>(Pdisp_total, digits<span class="op">=</span><span class="fl">2</span>), <span class="st">" cv"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P_disp,total = 35.63 cv</code></pre>
</div>
</div>
<aside><div>
<p>Multiplicar os dois fatores de correção é uma <strong>hipótese de independência</strong> (simplificação prática) — assume-se que o efeito das partidas frequentes e o efeito do ambiente atípico degradam a potência disponível de forma multiplicativa e independente um do outro. Não é uma dedução termodinâmica rigorosa (na realidade os dois efeitos interagem, já que ambos afetam a mesma capacidade de dissipação de calor), mas é a aproximação padrão usada na prática de especificação.</p>
</div></aside></section>
<section id="exemplo-do-texto-necessidade-de-trocar-o-motor" class="slide level2">
<h2>Exemplo do Texto: Necessidade de Trocar o Motor</h2>
<p>Se a potência disponível calculada ficar <strong>abaixo</strong> da demandada pela carga, sobe-se para o próximo motor comercial. Do texto original: <em>“um motor de 40 cv aciona sem problemas uma carga de 35 cv; contudo, se a potência disponível for de 30 cv, então é necessário selecionar um motor de 50 cv.”</em></p>
<div id="621f47bb" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href=""></a>Pnom_txt, Pcarga_txt, Pdisp_txt <span class="op">=</span> <span class="fl">40.0</span>, <span class="fl">35.0</span>, <span class="fl">30.0</span></span>
<span id="cb25-2"><a href=""></a></span>
<span id="cb25-3"><a href=""></a><span class="fu">println</span>(<span class="st">"Motor de 40 cv atende carga de 35 cv sem reducao? "</span>, Pnom_txt <span class="op">&gt;=</span> Pcarga_txt)</span>
<span id="cb25-4"><a href=""></a><span class="fu">println</span>(<span class="st">"Com reducao a P_disp=30 cv, ainda atende a carga de 35 cv? "</span>, Pdisp_txt <span class="op">&gt;=</span> Pcarga_txt)</span>
<span id="cb25-5"><a href=""></a><span class="fu">println</span>(Pdisp_txt <span class="op">&lt;</span> Pcarga_txt ? <span class="st">"-&gt; Necessario subir para o proximo motor comercial (50 cv)"</span> <span class="op">:</span> <span class="st">"-&gt; OK"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Motor de 40 cv atende carga de 35 cv sem reducao? true
Com reducao a P_disp=30 cv, ainda atende a carga de 35 cv? false
-&gt; Necessario subir para o proximo motor comercial (50 cv)</code></pre>
</div>
</div>
</section>
<section id="fator-de-serviço" class="slide level2">
<h2>Fator de Serviço</h2>
<p>Se a disponibilidade ficar <em>ligeiramente</em> abaixo da carga, uma alternativa a subir de potência é usar um motor de mesma potência com <strong>fator de serviço (F.S.) &gt; 1</strong>, tipicamente F.S. = 1,15.</p>
<p>Isso permite carga contínua de até 115% da potência nominal, sob condições especificadas — <strong>não confundir</strong> com a capacidade de sobrecarga momentânea (que dura apenas alguns minutos).</p>
</section>
<section id="especificação-de-grandezas-elétricas-tensão" class="slide level2">
<h2>Especificação de Grandezas Elétricas: Tensão</h2>
<p>A máquina deve ser compatível com a tensão da rede. Conforme os terminais disponíveis:</p>
<ul>
<li class="fragment"><strong>6 terminais:</strong> triângulo (220 V) ou estrela (380 V);</li>
<li class="fragment"><strong>9 terminais</strong> (meio-enrolamento acessível): paralelo (220 V) ou série (440 V);</li>
<li class="fragment"><strong>12 terminais</strong> (enrolamentos totalmente separados): tripla tensão (220/380/440 V).</li>
</ul>
<p>Motor com terminais já conectados de fábrica facilita a instalação, mas perde flexibilidade de tensão.</p>
</section>
<section id="exemplo-tensão-de-fase-e-de-linha" class="slide level2">
<h2>Exemplo: Tensão de Fase e de Linha</h2>
<p><em>Exemplo didático adicional (não consta no material original).</em></p>
<p>Enrolamento dimensionado para 220 V de fase, ligado em estrela — qual a tensão de linha correspondente?</p>
<div id="b3d9717b" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href=""></a>Vfase <span class="op">=</span> <span class="fl">220.0</span>   <span class="co"># V</span></span>
<span id="cb27-2"><a href=""></a>Vlinha <span class="op">=</span> Vfase <span class="op">*</span> <span class="fu">sqrt</span>(<span class="fl">3</span>)</span>
<span id="cb27-3"><a href=""></a><span class="fu">println</span>(<span class="st">"V_linha = "</span>, <span class="fu">round</span>(Vlinha, digits<span class="op">=</span><span class="fl">1</span>), <span class="st">" V  (fase = "</span>, Vfase, <span class="st">" V)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>V_linha = 381.1 V  (fase = 220.0 V)</code></pre>
</div>
</div>
<p>O resultado (≈ 381 V) explica por que motores de 220/380 V são tão comuns no Brasil: o mesmo enrolamento de 220 V, ligado em estrela, já fornece a tensão de linha padrão de 380 V da rede trifásica.</p>
</section>
<section id="frequência" class="slide level2">
<h2>Frequência</h2>
<p>Padrão brasileiro: 60 Hz. Abaixo da frequência nominal, reduz-se a tensão linearmente para manter o fluxo constante (evita saturação e sobrecorrente de magnetização):</p>
<p><span class="math display">\[
v(t) = -N \dfrac{d\phi(t)}{dt} \quad \rightarrow \quad \|\vec{\phi}\| = \dfrac{\|\vec{V}\|}{N \omega} = \text{constante}
\]</span></p>
<p>Acima da frequência nominal, a tensão é mantida constante (protege a isolação) e o fluxo — logo o conjugado máximo — diminui.</p>

<aside><div>
<p>Essa relação <strong>é</strong> dedução direta, não empírica: é a <strong>lei de Faraday</strong> (<span class="math inline">\(v=-N\,d\phi/dt\)</span>) para uma tensão senoidal, onde <span class="math inline">\(\|\vec{V}\| \propto N\omega\|\vec{\phi}\|\)</span>. Por isso manter <span class="math inline">\(V/\omega\)</span> (equivalente a <span class="math inline">\(V/f\)</span>) constante é exatamente o que preserva a amplitude do fluxo magnético — nenhum ajuste empírico aqui, é física de bobinas.</p>
</div></aside></section>
<section id="exemplo-tensão-em-frequência-reduzida-vf-constante" class="slide level2">
<h2>Exemplo: Tensão em Frequência Reduzida (V/f Constante)</h2>
<p>Motor com <span class="math inline">\(V_{\rm{nom}} = 380\)</span> V em <span class="math inline">\(f_{\rm{nom}} = 60\)</span> Hz, operado por inversor em <span class="math inline">\(f = 45\)</span> Hz mantendo <span class="math inline">\(V/f\)</span> constante:</p>
<div id="2a6a940b" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb29-1"><a href=""></a>Vnom, fnom <span class="op">=</span> <span class="fl">380.0</span>, <span class="fl">60.0</span></span>
<span id="cb29-2"><a href=""></a>fred <span class="op">=</span> <span class="fl">45.0</span></span>
<span id="cb29-3"><a href=""></a></span>
<span id="cb29-4"><a href=""></a>Vred <span class="op">=</span> Vnom <span class="op">*</span> (fred <span class="op">/</span> fnom)</span>
<span id="cb29-5"><a href=""></a><span class="fu">println</span>(<span class="st">"V em f = "</span>, fred, <span class="st">" Hz (V/f constante) = "</span>, <span class="fu">round</span>(Vred, digits<span class="op">=</span><span class="fl">1</span>), <span class="st">" V"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>V em f = 45.0 Hz (V/f constante) = 285.0 V</code></pre>
</div>
</div>
</section>
<section id="corrente" class="slide level2">
<h2>Corrente</h2>
<p>Corrente nominal em plena carga; se ficar consistentemente acima, motor subdimensionado; se ficar em 1/2 a 1/3 da nominal, superdimensionado.</p>
<p>Na partida direta: <strong>6 a 9 vezes</strong> <span class="math inline">\(I_{\rm{nom}}\)</span>. A norma limita a potência aparente com rotor bloqueado, em relação à potência nominal:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(P_{\rm{n}}\)</span> (kW)</th>
<th><span class="math inline">\(S_{\rm{p}}/P_{\rm{n}}\)</span> máx. (kVA/kW)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\leq 0{,}40\)</span></td>
<td>22</td>
</tr>
<tr class="even">
<td><span class="math inline">\(6{,}3 &lt; P_{\rm{n}} \leq 25\)</span></td>
<td>12</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(63 &lt; P_{\rm{n}} \leq 630\)</span></td>
<td>10</td>
</tr>
<tr class="even">
<td><span class="math inline">\(630 &lt; P_{\rm{n}} \leq 1600\)</span></td>
<td>9</td>
</tr>
</tbody>
</table>
</section>
<section id="exemplo-limite-de-corrente-de-partida" class="slide level2">
<h2>Exemplo: Limite de Corrente de Partida</h2>
<p>Motor com <span class="math inline">\(P_n = 10\)</span> kW (faixa <span class="math inline">\(6{,}3 &lt; P_n \leq 25\)</span> kW <span class="math inline">\(\Rightarrow S_p/P_n \leq 12\)</span> kVA/kW):</p>
<div id="4147bf4c" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb31-1"><a href=""></a>Pn <span class="op">=</span> <span class="fl">10.0</span>          <span class="co"># kW</span></span>
<span id="cb31-2"><a href=""></a>SpPn_max <span class="op">=</span> <span class="fl">12.0</span>    <span class="co"># kVA/kW, da tabela</span></span>
<span id="cb31-3"><a href=""></a></span>
<span id="cb31-4"><a href=""></a>Sp_max <span class="op">=</span> SpPn_max <span class="op">*</span> Pn</span>
<span id="cb31-5"><a href=""></a><span class="fu">println</span>(<span class="st">"S_p maximo com rotor bloqueado = "</span>, Sp_max, <span class="st">" kVA"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>S_p maximo com rotor bloqueado = 120.0 kVA</code></pre>
</div>
</div>
</section>
<section id="exemplo-sobrecorrente-ocasional" class="slide level2">
<h2>Exemplo: Sobrecorrente Ocasional</h2>
<p>Motores com <span class="math inline">\(P_{\rm{nom}} \leq 315\)</span> kW e <span class="math inline">\(V_{\rm{nom}} \leq 1\)</span> kV devem suportar <span class="math inline">\(1{,}5\,I_{\rm{nom}}\)</span> por pelo menos 2 minutos. Para <span class="math inline">\(I_{\rm{nom}} = 20\)</span> A:</p>
<div id="9be583af" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb33-1"><a href=""></a>Inom <span class="op">=</span> <span class="fl">20.0</span>   <span class="co"># A</span></span>
<span id="cb33-2"><a href=""></a>Iocasional <span class="op">=</span> <span class="fl">1.5</span> <span class="op">*</span> Inom</span>
<span id="cb33-3"><a href=""></a><span class="fu">println</span>(<span class="st">"Corrente ocasional admitida (&gt;= 2 min) = "</span>, Iocasional, <span class="st">" A"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Corrente ocasional admitida (&gt;= 2 min) = 30.0 A</code></pre>
</div>
</div>
</section>
<section id="especificação-de-parâmetros-construtivos" class="slide level2">
<h2>Especificação de Parâmetros Construtivos</h2>

<img data-src="images/vistaExplodidaMotorW22.svg" class="r-stretch quarto-figure quarto-figure-center" id="fig-vistaExplodida"><p class="caption">
Fig.&nbsp;8: Vista explodida de um motor trifásico.
</p></section>
<section id="ventilação" class="slide level2">
<h2>Ventilação</h2>
<ul>
<li><strong>Aberto</strong> (ODP — <em>Open Drip Proof</em>): melhor dissipação, ambientes limpos e secos;</li>
<li><strong>Totalmente Fechado com Ventilação Externa (TFVE):</strong>
<ul>
<li><strong>TEFC</strong> (autoventilado) — mais comum, mas depende da velocidade do próprio eixo;</li>
<li><strong>TENV</strong> (não ventilado);</li>
<li><strong>TEAO</strong> (refrigeração natural);</li>
<li><strong>TEFV</strong> (ventilação forçada) — indicado para baixas velocidades, onde o autoventilado esfria mal.</li>
</ul></li>
</ul>
<p>O tipo de ventilação define o fator <span class="math inline">\(k_{\rm{v}}\)</span> usado na <a href="#/eq-PefComRepouso" class="quarto-xref">Equação&nbsp;11</a>.</p>
</section>
<section id="grau-de-proteção-ip" class="slide level2">
<h2>Grau de Proteção (IP)</h2>
<p>Norma ABNT NBR-IEC 60034-5 — duas letras (IP) + dois algarismos: 1º = corpos estranhos, 2º = água.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>1º alg.</th>
<th>Indicação</th>
<th>2º alg.</th>
<th>Indicação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Não protegida</td>
<td>0</td>
<td>Não protegida</td>
</tr>
<tr class="even">
<td>2</td>
<td>Objetos &gt; 12 mm</td>
<td>1</td>
<td>Gotejamento vertical</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Objetos &gt; 1,0 mm</td>
<td>4</td>
<td>Projeções de água</td>
</tr>
<tr class="even">
<td>5</td>
<td>Poeira</td>
<td>5</td>
<td>Jatos de água</td>
</tr>
<tr class="odd">
<td>6</td>
<td>Totalmente contra poeira</td>
<td>7</td>
<td>Imersão temporária</td>
</tr>
</tbody>
</table>
<p>Motores abertos comuns: <strong>IP-21, IP-23</strong>. Motores fechados comuns: <strong>IP-44, IP-55</strong>. Aplicações especiais: <strong>IP-55W, IP-56, IP-65, IP-66</strong>.</p>
</section>
<section id="carcaça-e-formas-construtivas" class="slide level2">
<h2>Carcaça e Formas Construtivas</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div id="fig-tamanhoCarcaca" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-tamanhoCarcaca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/tamanhoCarcaca.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tamanhoCarcaca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;9: Tamanho <span class="math inline">\(H\)</span> da carcaça (mm).
</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div id="fig-elevacaoTemperatura" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-elevacaoTemperatura-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="images/elevacaoTemperaturaMotor.svg" class="quarto-figure quarto-figure-center" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-elevacaoTemperatura-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;10: Distribuição de temperatura no motor.
</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="formas-construtivas" class="slide level2">
<h2>Formas Construtivas</h2>

<img data-src="images/formaConstrutiva.svg" class="r-stretch quarto-figure quarto-figure-center" id="fig-formaConstrutiva"><p class="caption">
Fig.&nbsp;11: Formas construtivas de motores WEG.
</p><p>A mais comum é a <strong>B3D</strong>: montagem horizontal, motor com pés, eixo à direita (olhando para a caixa de ligação).</p>
</section>
<section id="tolerância-dos-parâmetros" class="slide level2">
<h2>Tolerância dos Parâmetros</h2>
<p>A NBR 17094 permite os seguintes desvios entre valor declarado e medido:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Grandeza</th>
<th>Tolerância</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rendimento (<span class="math inline">\(\eta \geq 0{,}851\)</span>)</td>
<td><span class="math inline">\(-0{,}2\,(1-\eta)\)</span></td>
</tr>
<tr class="even">
<td>Rendimento (<span class="math inline">\(\eta &lt; 0{,}851\)</span>)</td>
<td><span class="math inline">\(-0{,}15\,(1-\eta)\)</span></td>
</tr>
<tr class="odd">
<td>Fator de potência</td>
<td>entre <span class="math inline">\(-0{,}02\)</span> e <span class="math inline">\(-0{,}07\)</span></td>
</tr>
<tr class="even">
<td>Escorregamento (<span class="math inline">\(P_{\rm{nom}} \geq 1\)</span> kW)</td>
<td><span class="math inline">\(\pm 20\%\)</span></td>
</tr>
<tr class="odd">
<td>Corrente de partida</td>
<td><span class="math inline">\(+20\%\)</span></td>
</tr>
<tr class="even">
<td>Torque de partida / mínimo</td>
<td><span class="math inline">\(-15\%\)</span></td>
</tr>
<tr class="odd">
<td>Torque máximo</td>
<td><span class="math inline">\(-10\%\)</span> (mas <span class="math inline">\(\geq 1{,}5\,T_{\rm{nom}}\)</span>)</td>
</tr>
<tr class="even">
<td>Momento de inércia</td>
<td><span class="math inline">\(\pm 10\%\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="exemplo-tolerância-de-rendimento" class="slide level2">
<h2>Exemplo: Tolerância de Rendimento</h2>
<p>Motor com rendimento declarado <span class="math inline">\(\eta = 90\%\)</span> (<span class="math inline">\(\eta \geq 0{,}851 \Rightarrow\)</span> tolerância <span class="math inline">\(-0{,}2(1-\eta)\)</span>):</p>
<div id="943c1e33" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb35-1"><a href=""></a>eta <span class="op">=</span> <span class="fl">0.90</span></span>
<span id="cb35-2"><a href=""></a>delta_eta <span class="op">=</span> <span class="op">-</span><span class="fl">0.2</span> <span class="op">*</span> (<span class="fl">1</span> <span class="op">-</span> eta)</span>
<span id="cb35-3"><a href=""></a>eta_min <span class="op">=</span> eta <span class="op">+</span> delta_eta</span>
<span id="cb35-4"><a href=""></a></span>
<span id="cb35-5"><a href=""></a><span class="fu">println</span>(<span class="st">"Tolerancia = "</span>, <span class="fu">round</span>(delta_eta, digits<span class="op">=</span><span class="fl">4</span>))</span>
<span id="cb35-6"><a href=""></a><span class="fu">println</span>(<span class="st">"Rendimento medido deve ser &gt;= "</span>, <span class="fu">round</span>(eta_min, digits<span class="op">=</span><span class="fl">4</span>), <span class="st">" ("</span>, <span class="fu">round</span>(eta_min<span class="op">*</span><span class="fl">100</span>,digits<span class="op">=</span><span class="fl">2</span>), <span class="st">"%)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Tolerancia = -0.02
Rendimento medido deve ser &gt;= 0.88 (88.0%)</code></pre>
</div>
</div>
</section>
<section id="aspectos-econômicos" class="slide level2">
<h2>Aspectos Econômicos</h2>
<ul>
<li class="fragment">Especificação deve ser <strong>numérica e objetiva</strong> — evitar termos subjetivos como “baixas perdas” ou “elevado torque de partida”;</li>
<li class="fragment">Especificações mais genéricas (um tipo de motor para instalação diversa) são, paradoxalmente, <strong>mais difíceis</strong> de elaborar que uma aplicação específica;</li>
<li class="fragment">Custos totais: <strong>aquisição</strong> + <strong>energia</strong> (dominante ao longo da vida útil) + <strong>manutenção</strong> (preventiva e corretiva);</li>
<li class="fragment">Projeções de custo devem considerar a vida útil de todo o <strong>acionamento</strong>, não só do motor.</li>
</ul>
</section></section>
<section id="referências" class="title-slide slide level1 center">
<h1>Referências</h1>
<p>No material original, esta seção cita principalmente:</p>
<ul>
<li>LOBOSCO, O. S.; DIAS, J. L. P. C. (1988);</li>
<li>AUGUSTO JÚNIOR, C. (2005);</li>
<li>MAMEDE FILHO, J. (2017);</li>
<li>WEG — Guia de Especificação de Motores Elétricos (2021).</li>
</ul>
</section>

<section>
<section id="exercícios" class="title-slide slide level1 center">
<h1>Exercícios</h1>

</section>
<section id="exercício-1" class="slide level2">
<h2>Exercício 1</h2>
<p><strong>Um acionamento tem <span class="math inline">\(J=0{,}8\)</span> kg.m², <span class="math inline">\(\omega_{\rm{op}}=150\)</span> rad/s, dividido em 3 intervalos: <span class="math inline">\(\omega=[0, 75, 150]\)</span> rad/s com <span class="math inline">\(T_{\rm{ac}}=[100, 70, 50]\)</span> N.m. Calcule <span class="math inline">\(t_{\rm{ac}}\)</span> pelo método dos intervalos.</strong></p>
<div class="fragment">
<div id="3caf7975" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb37-1"><a href=""></a>omega <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">75.0</span>, <span class="fl">150.0</span>]</span>
<span id="cb37-2"><a href=""></a>Tac   <span class="op">=</span> [<span class="fl">100.0</span>, <span class="fl">70.0</span>, <span class="fl">50.0</span>]</span>
<span id="cb37-3"><a href=""></a>J <span class="op">=</span> <span class="fl">0.8</span></span>
<span id="cb37-4"><a href=""></a></span>
<span id="cb37-5"><a href=""></a>tac_total <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb37-6"><a href=""></a><span class="cf">for</span> k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(omega)<span class="op">-</span><span class="fl">1</span></span>
<span id="cb37-7"><a href=""></a>    Tbar <span class="op">=</span> (Tac[k<span class="op">+</span><span class="fl">1</span>] <span class="op">+</span> Tac[k]) <span class="op">/</span> <span class="fl">2</span></span>
<span id="cb37-8"><a href=""></a>    dt <span class="op">=</span> J <span class="op">/</span> Tbar <span class="op">*</span> (omega[k<span class="op">+</span><span class="fl">1</span>] <span class="op">-</span> omega[k])</span>
<span id="cb37-9"><a href=""></a>    <span class="kw">global</span> tac_total <span class="op">+=</span> dt</span>
<span id="cb37-10"><a href=""></a><span class="cf">end</span></span>
<span id="cb37-11"><a href=""></a><span class="fu">println</span>(<span class="st">"t_ac total = "</span>, <span class="fu">round</span>(tac_total, digits<span class="op">=</span><span class="fl">4</span>), <span class="st">" s"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>t_ac total = 1.7059 s</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-2" class="slide level2">
<h2>Exercício 2</h2>
<p><strong>Um motor categoria D tem <span class="math inline">\(T_{\rm{e,p}}=250\)</span> N.m. Calcule seu torque médio eletromagnético <span class="math inline">\(\overline{T}_{\rm{e}}\)</span>.</strong></p>
<div class="fragment">
<div id="002c9930" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb39-1"><a href=""></a>Tep_D <span class="op">=</span> <span class="fl">250.0</span></span>
<span id="cb39-2"><a href=""></a>Tebar_D <span class="op">=</span> <span class="fl">0.60</span> <span class="op">*</span> Tep_D</span>
<span id="cb39-3"><a href=""></a><span class="fu">println</span>(<span class="st">"T_e_bar (categoria D) = "</span>, Tebar_D, <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T_e_bar (categoria D) = 150.0 N.m</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-3" class="slide level2">
<h2>Exercício 3</h2>
<p><strong>Uma carga com torque quadrático (<span class="math inline">\(\beta=2\)</span>) tem <span class="math inline">\(T_{\rm{L,p}}=20\)</span> N.m e <span class="math inline">\(T_{\rm{L,op}}=180\)</span> N.m. Calcule <span class="math inline">\(\overline{T}_{\rm{L}}\)</span>.</strong></p>
<div class="fragment">
<div id="28f72f4c" class="cell" data-execution_count="22">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb41-1"><a href=""></a>TLp, TLop, beta <span class="op">=</span> <span class="fl">20.0</span>, <span class="fl">180.0</span>, <span class="fl">2</span></span>
<span id="cb41-2"><a href=""></a>TLbar <span class="op">=</span> TLp <span class="op">+</span> (TLop <span class="op">-</span> TLp)<span class="op">/</span>(beta<span class="op">+</span><span class="fl">1</span>)</span>
<span id="cb41-3"><a href=""></a><span class="fu">println</span>(<span class="st">"T_L_bar = "</span>, <span class="fu">round</span>(TLbar, digits<span class="op">=</span><span class="fl">2</span>), <span class="st">" N.m"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>T_L_bar = 73.33 N.m</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-4" class="slide level2">
<h2>Exercício 4</h2>
<p><strong>Um ciclo de carga tem 2 patamares: 15 kW por 40 s e 30 kW por 10 s, sem repouso. Calcule a potência eficaz e compare com o pico.</strong></p>
<div class="fragment">
<div id="4961a7e3" class="cell" data-execution_count="23">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb43-1"><a href=""></a>PLi <span class="op">=</span> [<span class="fl">15.0</span>, <span class="fl">30.0</span>]</span>
<span id="cb43-2"><a href=""></a>ti  <span class="op">=</span> [<span class="fl">40.0</span>, <span class="fl">10.0</span>]</span>
<span id="cb43-3"><a href=""></a>Pef <span class="op">=</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(PLi<span class="op">.^</span><span class="fl">2</span> <span class="op">.*</span> ti) <span class="op">/</span> <span class="fu">sum</span>(ti))</span>
<span id="cb43-4"><a href=""></a><span class="fu">println</span>(<span class="st">"P_ef = "</span>, <span class="fu">round</span>(Pef, digits<span class="op">=</span><span class="fl">3</span>), <span class="st">" kW (pico = "</span>, <span class="fu">maximum</span>(PLi), <span class="st">" kW)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P_ef = 18.974 kW (pico = 30.0 kW)</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-5" class="slide level2">
<h2>Exercício 5</h2>
<p><strong>Um motor de <span class="math inline">\(P_{\rm{nom}}=25\)</span> cv opera com <span class="math inline">\(N_p=6\)</span> partidas/hora, <span class="math inline">\(t_{\rm{ac}}=5\)</span> s e <span class="math inline">\(I_p/I_{\rm{nom}}=6\)</span>. Calcule a potência disponível <span class="math inline">\(P_{\rm{disp,pfr}}\)</span>.</strong></p>
<div class="fragment">
<div id="3562725d" class="cell" data-execution_count="24">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb45-1"><a href=""></a>kpfr, Np, tac_h, Ip_Inom, Pnom <span class="op">=</span> <span class="fl">1.0</span>, <span class="fl">6.0</span>, <span class="fl">5.0</span>, <span class="fl">6.0</span>, <span class="fl">25.0</span></span>
<span id="cb45-2"><a href=""></a>alpha_pfr <span class="op">=</span> <span class="fu">sqrt</span>((<span class="fl">3600</span> <span class="op">-</span> <span class="fu">kpfr*Np*tac_h*</span>(Ip_Inom)<span class="op">^</span><span class="fl">2</span>) <span class="op">/</span> (<span class="fl">3600</span> <span class="op">-</span> <span class="fl">2</span><span class="op">*</span>Np<span class="op">*</span>tac_h))</span>
<span id="cb45-3"><a href=""></a><span class="fu">println</span>(<span class="st">"alpha_pfr = "</span>, <span class="fu">round</span>(alpha_pfr, digits<span class="op">=</span><span class="fl">4</span>))</span>
<span id="cb45-4"><a href=""></a><span class="fu">println</span>(<span class="st">"P_disp,pfr = "</span>, <span class="fu">round</span>(alpha_pfr<span class="op">*</span>Pnom, digits<span class="op">=</span><span class="fl">2</span>), <span class="st">" cv"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>alpha_pfr = 0.8437
P_disp,pfr = 21.09 cv</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-6" class="slide level2">
<h2>Exercício 6</h2>
<p><strong>Explique por que um motor autoventilado (TEFC) é uma má escolha para operar continuamente em baixas velocidades.</strong></p>
<div class="fragment">
<p>Porque o ventilador está acoplado ao próprio eixo — em baixa velocidade, o ventilador gira devagar e a vazão de ar cai proporcionalmente, prejudicando a dissipação de calor justamente quando o motor mais precisa de refrigeração. A alternativa é usar ventilação forçada (TEFV), com fonte de ar independente da rotação do motor.</p>
</div>
</section>
<section id="exercício-7" class="slide level2">
<h2>Exercício 7</h2>
<p><strong>Um motor tem rendimento declarado <span class="math inline">\(\eta=80\%\)</span> (abaixo de 0,851, tolerância <span class="math inline">\(-0{,}15(1-\eta)\)</span>). Qual o rendimento mínimo aceitável medido?</strong></p>
<div class="fragment">
<div id="b6c528e1" class="cell" data-execution_count="25">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb47-1"><a href=""></a>eta <span class="op">=</span> <span class="fl">0.80</span></span>
<span id="cb47-2"><a href=""></a>delta_eta <span class="op">=</span> <span class="op">-</span><span class="fl">0.15</span><span class="fu">*</span>(<span class="fl">1</span><span class="op">-</span>eta)</span>
<span id="cb47-3"><a href=""></a>eta_min <span class="op">=</span> eta <span class="op">+</span> delta_eta</span>
<span id="cb47-4"><a href=""></a><span class="fu">println</span>(<span class="st">"Tolerancia = "</span>, <span class="fu">round</span>(delta_eta, digits<span class="op">=</span><span class="fl">4</span>))</span>
<span id="cb47-5"><a href=""></a><span class="fu">println</span>(<span class="st">"Rendimento medido deve ser &gt;= "</span>, <span class="fu">round</span>(eta_min, digits<span class="op">=</span><span class="fl">4</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Tolerancia = -0.03
Rendimento medido deve ser &gt;= 0.77</code></pre>
</div>
</div>
</div>
</section>
<section id="exercício-8" class="slide level2">
<h2>Exercício 8</h2>
<p><strong>Por que a especificação técnica de um motor não deve conter termos como “baixas perdas” ou “operação livre de falha”?</strong></p>
<div class="fragment">
<p>Porque são termos subjetivos, sem valor numérico verificável — não permitem ao fabricante saber exatamente o que deve ser entregue, nem ao comprador verificar se o produto atende à especificação. Uma boa especificação comunica de forma clara e numérica o que precisa ser alcançado, não como alcançá-lo.</p>
</div>
</section></section>
<section id="obrigado" class="title-slide slide level1 center">
<h1>Obrigado!</h1>
<div style="text-align: center;">
<p><a href="http://thalesmaia.com/">http://thalesmaia.com/</a></p>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>UFMG | ELE618 - Sistemas Elétricos Industriais</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: true,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'bottom-right',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>